# Generated by Django 2.0 on 2017-12-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('like', models.IntegerField()),
                ('color', models.CharField(max_length=27)),
                ('userid', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=40, null=True)),
                ('colortype', models.CharField(max_length=50, null=True)),
                ('display', models.BooleanField()),
                ('createdate', models.DateTimeField()),
            ],
        ),
    ]
