# Generated by Django 2.0 on 2018-01-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colorpk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('oauth', models.SlugField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('oauthid', models.CharField(max_length=30)),
                ('isadmin', models.BooleanField()),
                ('lastlogin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colorpk.Color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colorpk.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userlike',
            unique_together={('user', 'color')},
        ),
    ]
