name: CI

on:
  push:
    paths:
      - '.github/**'
      - 'client/**'
      - 'package.json'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install npm
        run: npm i
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build js
        run: npm run build
      - name: setup aliyun oss
        if: false
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: ${{ secrets.oss_region }}
          access-key-id: ${{ secrets.oss_app_key }}
          access-key-secret: ${{ secrets.oss_app_secret }}
      - name: cp files to aliyun
        if: false
        run: ossutil cp -rf static oss://${{ secrets.oss_bucket }}/4/ --meta=Cache-Control:"public, max-age=1728002"#Content-Encoding:gzip --include "*.css" --include "*.js"
